### PR TITLE
fix #1083: succeed binding to system and conda base python installation

### LINKED ISSUE #1083: Windows-installed python is not correctly detected
I am on a Windows 10 computer and I have the version of python installed through Windows Store. 
This is from here: https://docs.python.org/3/using/windows.html#the-microsoft-store-package 

This is what works on my system and where it is located
```powershell
❯ py.exe -0p
Installed Pythons found by C:\Windows\py.exe Launcher for Windows
 -3.9-64        C:\Users\chris\AppData\Local\Programs\Python\Python39\python.exe *
```

Having this version works in terminal and also with Quarto 
````powershell
❯ quarto check jupyter

[>] Checking Python 3 installation....OK
      Version: 3.9.5
      Path: C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe
      Jupyter: 4.7.1
      Kernels: python3

[>] Checking Jupyter engine render....OK
````

However, with reticulate, this version is not correctly found
````r
> reticulate::py_discover_config()
Error: could not find a Python environment for C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error: could not find a Python environment for C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe
Backtrace:
 1. reticulate::py_discover_config()
 2. reticulate:::python_config(python_version, required_module, python_versions)
 3. reticulate:::python_munge_path(python)
 4. reticulate:::python_info(python)
 5. reticulate:::stopf(...)
Run `rlang::last_trace()` to see the full context.
````

It seems like `python_info()` expect an environment or else, and in any case doesn't know how to retrieve information on this one. 

Creating a virtualenv  manually and activating it solve the issue with the installation 
```r
# reticulate::virtualenv_create("r-reticulate")
> reticulate::use_virtualenv("r-reticulate")
master* > reticulate::py_discover_config()
python:         C:/Users/chris/Documents/.virtualenvs/r-reticulate/Scripts/python.exe
libpython:      C:/Users/chris/AppData/Local/Programs/Python/Python39/python39.dll
pythonhome:     C:/Users/chris/Documents/.virtualenvs/r-reticulate
version:        3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/chris/Documents/.virtualenvs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.21.4

python versions found: 
 C:/Users/chris/Documents/.virtualenvs/r-reticulate/Scripts/python.exe
 C:/Users/chris/AppData/Local/Programs/Python/Python39/python.exe
```

### PR DESCRIPTION
**Pull request by t-kalinowski**
+ wrap `python_info()` in `tryCatch()`, since it errors on a non-env python
+ Allow `conda_run()` to succeed in a conda base environment

### CODE REVIEW

**Comment by t-kalinowski** [comment]
I just noticed all the whitespace changes accidentally snuck in there when I rebased.
Sorry about that! let me know if you'd prefer I undo them.

**Comment by t-kalinowski** [comment]
also fixes: #1091

File: R/conda.R [hunk 1]
```diff
@@ -758,17 +758,21 @@ conda_run <- function(cmd, args = c(), conda = "auto", envname = NULL,
                       run_args = c("--no-capture-output"), ...) {
 
   conda <- conda_binary(conda)
-  envname <- condaenv_resolve(envname)
+  if(!identical(envname, "base"))
+    envname <- condaenv_resolve(envname)
```
Comment (kevinushey) [inline R/conda.R:762]: I wonder if this check should be part of `condaenv_resolve()` itself? (So that `condaenv_resolve("base")` always returns "base")

File: R/conda.R [hunk 2]
```diff
@@ -758,17 +758,21 @@ conda_run <- function(cmd, args = c(), conda = "auto", envname = NULL,
...
 
   if (numeric_conda_version(conda) < "4.9")
     stopf(
 "`conda_run()` requires conda version >= 4.9.
 Run `miniconda_update('%s')` to update conda.", conda)
 
-  if(grepl("[/\\]", envname))
+  if(envname == "base") 
+    in_env <- ""
```
Comment (kevinushey) [inline R/conda.R:770]: Can we still set a prefix here explicitly? My worry is that the user might have the `CONDA_PREFIX` environment variable defined (https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-that-affect-the-build-process) and that could override an attempt to use the base environment.

Alternatively, we might need to unset that environment variable before running Conda. What do you think?

**Review by kevinushey — COMMENTED** [review]
Overall LGTM, but I think two changes warrant a bit of discussion. Thanks for putting this together!

File: R/conda.R (hunk 2 above)
Comment (t-kalinowski) [reply R/conda.R:770]: Thank you for your comments. I hadn't realized that you can explicitly request the base env by name.

I removed all the special handling for `envname = "base"` in `conda_run()`. 
`condaenv_resolve()` already does the right thing where `condaenv_resolve("base") == "base"`, and `/path/to/conda run --name base ...` works also. 

I also confirmed that the command line argument `--name base` takes precedence over the env var `CONDA_PREFIX`.

**Comment by kevinushey** [comment]
LGTM; thank you!
