### PR TITLE
make the requirement of `bash` explicit; fix #1306

### LINKED ISSUE #1306: Linux/OSX: `install_miniconda`  has a hidden assumption of requiring `/bin/sh` links to `bash`
Thank you very much for the package!

Due to this issue of the upstream conda: conda/conda#10431

The miniconda installer actually requires `bash`. On a `focal` (current Ubuntu LTS) system, the default `/bin/sh` can't understand some `bash` specific commands, e.g. `[[`. [The page listing all the installers](https://docs.conda.io/en/latest/miniconda.html#linux-installers) makes it very explicit that some are `bash` installers.

Until the above issue is fixed, I suggest changing this line:

https://github.com/rstudio/reticulate/blob/bb2ed00609437dc8bcacb0cc34849177e4573a17/R/miniconda.R#L238

To explicitly running `bash` instead. A PR is forthcoming.

Reprex

``` r
reticulate::install_miniconda()
#> * Installing Miniconda -- please wait a moment ...
#> * Downloading 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh' ...
#> Error: miniconda installation failed [exit code 1]
sessionInfo()
#> R version 4.2.2 Patched (2022-11-10 r83330)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04.1 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.9        knitr_1.39        magrittr_2.0.3    rappdirs_0.3.3   
#>  [5] lattice_0.20-45   R.cache_0.16.0    rlang_1.0.6       fastmap_1.1.0    
#>  [9] fansi_1.0.3       stringr_1.4.1     styler_1.7.0      highr_0.9        
#> [13] tools_4.2.2       grid_4.2.2        xfun_0.31         png_0.1-7        
#> [17] R.oo_1.25.0       utf8_1.2.2        cli_3.4.1         withr_2.5.0      
#> [21] htmltools_0.5.3   yaml_2.3.6        digest_0.6.30     tibble_3.1.8     
#> [25] lifecycle_1.0.3   Matrix_1.5-1      purrr_0.3.5       vctrs_0.5.1      
#> [29] R.utils_2.12.0    fs_1.5.2          glue_1.6.2        evaluate_0.15    
#> [33] rmarkdown_2.14    reprex_2.0.1      stringi_1.7.8     compiler_4.2.2   
#> [37] pillar_1.8.1      R.methodsS3_1.8.2 jsonlite_1.8.3    reticulate_1.26  
#> [41] pkgconfig_2.0.3
```

<sup>Created on 2022-12-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by chainsawriot**

### CODE REVIEW

File: R/miniconda.R [hunk 1]
```diff
@@ -234,8 +234,16 @@ miniconda_installer_run <- function(installer, update, path) {
     on.exit(Sys.setenv(DYLD_FALLBACK_LIBRARY_PATH = old), add = TRUE)
 
   }
-
-  status <- system2(installer, args)
+  if (is_windows())
+    status <- system2(installer, args)
+  if (is_unix()) {
+    ##check for bash
+    bash_available <- system2("bash", "--version")
```
Comment (kevinushey) [inline R/miniconda.R:241]: I think you can use `Sys.which()` instead.

File: R/miniconda.R [hunk 2]
```diff
@@ -234,8 +234,16 @@ miniconda_installer_run <- function(installer, update, path) {
...
+    if (bash_available != 0)
+      stopf("bash is not available.")
```
Comment (kevinushey) [inline R/miniconda.R:243]: We should emphasize that the Miniconda installer appears to require `bash` (rather than `sh`) in this error message.

File: R/miniconda.R (hunk 1 above)
Comment (kevinushey) [reply R/miniconda.R:241]: I also wonder if we should respect the `SHELL` environment variable.

**Comment by chainsawriot** [comment]
@kevinushey Thank you for the review. I hope the above addressed the issues.

**Comment by t-kalinowski** [comment]
Thank you for the PR!

I can reproduce the error locally:
```r
> reticulate::install_miniconda()
* Installing Miniconda -- please wait a moment ...
PREFIX=/home/tomasz/.local/share/r-miniconda
Unpacking payload ...
                                                                                                                
Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: ...working... done
Executing transaction: ...working... done

Installing * environment...

/tmp/RtmphkIUOD/Miniconda3-latest-Linux-x86_64.sh: 438: [[: not found
/tmp/RtmphkIUOD/Miniconda3-latest-Linux-x86_64.sh: 444: [[: not found

CondaFileIOError: '/home/tomasz/.local/share/r-miniconda/pkgs/envs/*/env.txt'. [Errno 2] No such file or directory: '/home/tomasz/.local/share/r-miniconda/pkgs/envs/*/env.txt'

Error: miniconda installation failed [exit code 1]
```

The [installation instructions](https://conda.io/projects/conda/en/stable/user-guide/install/linux.html) show that the installer script is meant to be passed directly to bash, and not run as an executable.

The `#!/bin/sh` shebang directive is best ignored it seems:
```r
readLines(url("https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"), 1)
[1] "#!/bin/sh"
```


The patch looks good, I agree that `Sys.which("bash")` is the way to go.

Can you please add a NEWS entry?

**Review by t-kalinowski — APPROVED** [review]
LGTM!

**Comment by chainsawriot** [comment]
@t-kalinowski NEWS Updated. The failed tests weren't related to this PR.

**Comment by t-kalinowski** [comment]
Thank you!
